### PR TITLE
Return all flags for underlying type MaxValue

### PR DESCRIPTION
**Pull request by syedsuhaib**
When FromValue() is called on a SmartFlagEnum with the corresponding MaxValue of the base type as the value argument, a list of all defined enum values is returned. This is similar to passing negative one.

I have retained the negative one functionality. Just a simple addition to see whether we're on the same page regarding the direction I am taking.

I also wrote a test to check the functionality and it passes! We could probably write a couple more, but I am being lazy ;)

### CODE REVIEW

**Comment by syedsuhaib** [comment]
I've marked this PR as a draft. Just checking if you're still able to see it @AFM-Horizon?

**Comment by AFM-Horizon** [comment]
> 
> 
> I've marked this PR as a draft. Just checking if you're still able to see it @AFM-Horizon?

Yes Mate I Can.  Looks Good! I thought It would have been harder to implement I guess the code isn't to messy and hard to understand after all haha! If the current test pass we should be ok! I'll have a look over it tonight.  I have to fix some conflicts in my fork to the master before i can pull the changes in as steve has updated some stuff by the looks of it (not the files we are working on though). Thanks!! :)

**Comment by syedsuhaib** [comment]
Of course the code is not messy but the sheer volume of it is a bit intimidating at first. Took me a while to figure where's what. I almost confused your GetMaxAllowedValue for the MaxValue that I implemented. Come to think of it, these both will return all flags but I had to look for what is available to the consumer outside of the current assembly. `<type>.MaxValue` will always be accessible to the calling user.

**Comment by AFM-Horizon** [comment]
@syedsuhaib Hey mate I Just finished mucking around and pulling in the changes from the upstream branch.  Unfortunately they changed the file structure so that the test projects are in their own folder now and this meant for me that i had to move some stuff around to get it working and up to date.  It may be easier rather than dealing with that to just create a new fork off the current one and re add the changes on that.  Apologies for the inconvenience! 👎 Once you are up to date/or have dealt with the conflicts I will pull the change in!  
Cheers!

**Pull request merged**
